// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EntityForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"form-section\"><h2 style=\"text-align: center;\">Agregar Nuevo Juego</h2><form id=\"createGameForm\" class=\"game-form\" method=\"POST\" action=\"/games\" hx-post=\"/games\" hx-target=\"#gamesList\" hx-swap=\"outerHTML\"><input type=\"text\" id=\"gameTitle\" name=\"title\" placeholder=\"Título\" required> <input type=\"text\" id=\"gameDescription\" name=\"description\" placeholder=\"Descripción\" required> <input type=\"text\" id=\"gameCategory\" name=\"category\" placeholder=\"Categoría\" required> <input type=\"date\" id=\"gameDate\" name=\"release_date\" placeholder=\"Fecha de salida\" required> <select id=\"gameState\" name=\"state\" required><option value=\"\">-- Seleccioná un estado --</option> <option value=\"none\">None</option> <option value=\"deseado\">Deseado</option> <option value=\"comprado\">Completado</option></select> <button type=\"submit\" class=\"btn-primary\">Agregar Juego</button></form></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
