// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Game struct {
	ID          int32        `json:"id"`
	Titulo      string       `json:"titulo"`
	Descripcion string       `json:"descripcion"`
	Categoria   string       `json:"categoria"`
	Fecha       time.Time    `json:"fecha"`
	Estado      string       `json:"estado"`
	Imagen      string       `json:"imagen"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
