// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (titulo, descripcion, categoria, fecha, estado, imagen)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, titulo, descripcion, categoria, to_char(fecha, 'YYYY-MM-DD') AS fecha, estado, imagen, created_at
`

type CreateGameParams struct {
	Titulo      string    `json:"titulo"`
	Descripcion string    `json:"descripcion"`
	Categoria   string    `json:"categoria"`
	Fecha       time.Time `json:"fecha"`
	Estado      string    `json:"estado"`
	Imagen      string    `json:"imagen"`
}

type CreateGameRow struct {
	ID          int32        `json:"id"`
	Titulo      string       `json:"titulo"`
	Descripcion string       `json:"descripcion"`
	Categoria   string       `json:"categoria"`
	Fecha       string       `json:"fecha"`
	Estado      string       `json:"estado"`
	Imagen      string       `json:"imagen"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (CreateGameRow, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Titulo,
		arg.Descripcion,
		arg.Categoria,
		arg.Fecha,
		arg.Estado,
		arg.Imagen,
	)
	var i CreateGameRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Categoria,
		&i.Fecha,
		&i.Estado,
		&i.Imagen,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGame = `-- name: DeleteGame :one
DELETE FROM games
WHERE id = $1
RETURNING id, titulo, descripcion, categoria, fecha, estado, imagen, created_at
`

func (q *Queries) DeleteGame(ctx context.Context, id int32) (Game, error) {
	row := q.db.QueryRowContext(ctx, deleteGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Categoria,
		&i.Fecha,
		&i.Estado,
		&i.Imagen,
		&i.CreatedAt,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
SELECT id, titulo, descripcion, categoria, to_char(fecha, 'YYYY-MM-DD') AS fecha, estado, imagen, created_at
FROM games
WHERE id = $1
`

type GetGameRow struct {
	ID          int32        `json:"id"`
	Titulo      string       `json:"titulo"`
	Descripcion string       `json:"descripcion"`
	Categoria   string       `json:"categoria"`
	Fecha       string       `json:"fecha"`
	Estado      string       `json:"estado"`
	Imagen      string       `json:"imagen"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

func (q *Queries) GetGame(ctx context.Context, id int32) (GetGameRow, error) {
	row := q.db.QueryRowContext(ctx, getGame, id)
	var i GetGameRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Categoria,
		&i.Fecha,
		&i.Estado,
		&i.Imagen,
		&i.CreatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, titulo, descripcion, categoria, to_char(fecha, 'YYYY-MM-DD') AS fecha, estado, imagen, created_at
FROM games
ORDER BY titulo
`

type ListGamesRow struct {
	ID          int32        `json:"id"`
	Titulo      string       `json:"titulo"`
	Descripcion string       `json:"descripcion"`
	Categoria   string       `json:"categoria"`
	Fecha       string       `json:"fecha"`
	Estado      string       `json:"estado"`
	Imagen      string       `json:"imagen"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

func (q *Queries) ListGames(ctx context.Context) ([]ListGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGamesRow
	for rows.Next() {
		var i ListGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Categoria,
			&i.Fecha,
			&i.Estado,
			&i.Imagen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWantedGames = `-- name: ListWantedGames :many
SELECT id, titulo, descripcion, categoria, to_char(fecha, 'YYYY-MM-DD') AS fecha, estado, imagen, created_at
FROM games
WHERE estado = 'deseado'
ORDER BY titulo
`

type ListWantedGamesRow struct {
	ID          int32        `json:"id"`
	Titulo      string       `json:"titulo"`
	Descripcion string       `json:"descripcion"`
	Categoria   string       `json:"categoria"`
	Fecha       string       `json:"fecha"`
	Estado      string       `json:"estado"`
	Imagen      string       `json:"imagen"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

func (q *Queries) ListWantedGames(ctx context.Context) ([]ListWantedGamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listWantedGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWantedGamesRow
	for rows.Next() {
		var i ListWantedGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descripcion,
			&i.Categoria,
			&i.Fecha,
			&i.Estado,
			&i.Imagen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET titulo = $2, descripcion = $3, categoria = $4, fecha = $5, estado = $6, imagen = $7
WHERE id = $1
RETURNING id, titulo, descripcion, categoria, fecha, estado, imagen, created_at
`

type UpdateGameParams struct {
	ID          int32     `json:"id"`
	Titulo      string    `json:"titulo"`
	Descripcion string    `json:"descripcion"`
	Categoria   string    `json:"categoria"`
	Fecha       time.Time `json:"fecha"`
	Estado      string    `json:"estado"`
	Imagen      string    `json:"imagen"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame,
		arg.ID,
		arg.Titulo,
		arg.Descripcion,
		arg.Categoria,
		arg.Fecha,
		arg.Estado,
		arg.Imagen,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Categoria,
		&i.Fecha,
		&i.Estado,
		&i.Imagen,
		&i.CreatedAt,
	)
	return i, err
}

const updateGameState = `-- name: UpdateGameState :one
UPDATE games
SET estado = $2
WHERE id = $1
RETURNING id, titulo, descripcion, categoria, fecha, estado, imagen, created_at
`

type UpdateGameStateParams struct {
	ID     int32  `json:"id"`
	Estado string `json:"estado"`
}

func (q *Queries) UpdateGameState(ctx context.Context, arg UpdateGameStateParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGameState, arg.ID, arg.Estado)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descripcion,
		&i.Categoria,
		&i.Fecha,
		&i.Estado,
		&i.Imagen,
		&i.CreatedAt,
	)
	return i, err
}
