FROM golang

WORKDIR /app

COPY tp-web-logica/ tp-web-logica/
COPY tp-web-datos/ tp-web-datos/

WORKDIR /app/tp-web-logica

RUN go mod download

RUN go build -o /app/api-go

EXPOSE 8081

CMD ["/app/api-go"]